(print "=== Platform Calls Demo ===")
(print "")

(print "1. system:")
(system "echo 'Hello from Lisp!'")
(print "")

(print "2. Working directory:")
(print "Current:")
(print (getcwd))
(chdir "/tmp")
(print "Changed to /tmp:")
(print (getcwd))
(chdir "/home")
(print "Changed to /home:")
(print (getcwd))
(print "")

(print "3. Environment variables:")
(print "HOME:")
(print (getenv "HOME"))
(print "USER:")
(print (getenv "USER"))
(setenv "LISP_VAR" "42")
(print "LISP_VAR:")
(print (getenv "LISP_VAR"))
(unsetenv "LISP_VAR")
(print "LISP_VAR after unset:")
(print (getenv "LISP_VAR"))
(print "")

(print "4. Process Info:")
(print "PID:")
(print (getpid))
(print "")

(print "5. Time:")
(print "Seconds since epoch:")
(print (time))
(print "")

(print "6. Sleep:")
(print "Waiting 2 seconds...")
(sleep 2)
(print "Done!")
(print "")

(print "7. Countdown:")
(defun countdown (n)
    (progn 
        (if (> n 0)
            (print n)
            nil)
        (if (> n 1)
            (sleep 1)
            nil)
        (if (> n 1)
            (countdown (- n 1))
            nil)
        )
)
(countdown 3)
(print "")

(print "8. System Info:")
(defun sysinfo ()
    (progn 
        (print "=== System Information ===")
        (print "PID:")
        (print (getpid))
        (print "PWD:")
        (print (getcwd))
        (print "HOME:")
        (print (getenv "HOME"))
        (print "USER:")
        (print (getenv "USER"))
        (print "SHELL:")
        (print (getenv "SHELL"))
        (print "TIME:")
        (print (time))
        (print "===")
    )
)
(sysinfo)
(print "")

(print "9. Running shell command:")
(defun run_ls ()
    (system "ls -la /tmp | head -5"))
(run_ls)
(print "")

(print "11. Platform Info:")
(defun platform_info ()
    (progn
        (print "=== Platform ===")
        (system "uname -a")
        (print "=== End ===")
    )
)
(platform_info)
(print "")

(print "12. Creating test file:")
(system "echo 'Hello from Lisp!' > /tmp/lisp-test.txt")
(system "cat /tmp/lisp-test.txt")
(system "rm /tmp/lisp-test.txt")
(print "")

(print "13. Directory listing (first 3 lines):")
(system "ls -la /home | head -3")
(print "")

(print "14. System uptime:")
(system "uptime")
(print "")

(print "15. Memory info (first 3 lines):")
(system "free -h | head -3")
(print "")

(print "16. Exit demo (commented):")
(print "  (exit 0) would exit here")
(print "")

(print "=== All demos completed ===")