(print "1. Basic logic:")
(print (and t t))
(print (and t nil))
(print (and t t t t))
(print (and t t nil t))
(print (or t nil))
(print (or nil nil))
(print (or nil t nil))
(print (or nil nil t))
(print "")

(print "2. Return values:")
(print (and 1 2 3))
(print (and nil 42))
(print (or 1 2 3))
(print (or nil 2 3))
(print (or nil nil 42))
(print "")

(print "3. Range check:")
(defun in_range (x low high)
    (and (>= x low) (<= x high)))

(print (in_range 5 0 10))
(print (in_range -5 0 10))
(print (in_range 15 0 10))
(print "")